import type { Metadata } from "next";
import { Creepster } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navbar";
import ScaryBackground from "@/components/global/scarybg";
import Footer from "@/components/global/footer";

const geistSans = Creepster({
  weight: "400",
  variable: "--font-regular",
  subsets: ["latin"],
  display: "swap",
});

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Anveshan 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  antialiased bg-black`}>
        <ScaryBackground />

        <Navbar />

        <div className="pt-20"></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
